### ISSUE TITLE
Client-Side IRC server choice?

### ISSUE THREAD

**Issue by clort81** [theZiz/hase#13]
Wow, works great now!  Except chat.  Freenode now requires SASL login from most countries, which is an unnecessary barrier.

While it does look easy to host one's own Hase server (documented in server.md (thanks)) I wonder if perhaps client/user could specify an alternate IRC server to chat in?

(aside) Did you upgrade the music?  The main theme sounds punchier to me somehow.  Cheers!

**Comment by theZiz** [comment]
Hm, right now you can only change the chat server by using an own entry page as described here:
https://github.com/theZiz/hase/blob/master/server.md#how-to-tell-hase-about-the-server

Nevertheless you would need to host this somewhere yourself although you can still link to my server as game server.

I could add an option to overwrite this chat setting in the options file. Or I change the whole location of the IRC channel. Right now nobody is online anyway, so I could also just move to an IRC server which is nicer to my users like euirc or quakenet. <_<

**Comment by theZiz** [comment]
Okay, I changed the official server to the euirc. While doing this I also had to fix a bug in sparrow3d. Furthermore I added your desired option. :)

**Comment by clort81** [comment]
Oh!  Thank you!
